// Mock Convex generated API
export const api = {
  users: {
    updateProfile: 'users:updateProfile',
    addSkill: 'users:addSkill',
    removeSkill: 'users:removeSkill',
    getCurrentUser: 'users:getCurrentUser',
    getUserById: 'users:getUserById',
    searchUsers: 'users:searchUsers',
    createUserFromWebhook: 'users:createUserFromWebhook',
    updateUserFromWebhook: 'users:updateUserFromWebhook',
    getUserByUsername: 'users:getUserByUsername',
    updateNotificationPreferences: 'users:updateNotificationPreferences',
  },
  calls: {
    initiateCall: 'calls:initiateCall',
    acceptCall: 'calls:acceptCall',
    rejectCall: 'calls:rejectCall',
    endCall: 'calls:endCall',
    getCallHistory: 'calls:getCallHistory',
    getActiveCall: 'calls:getActiveCall',
    getIncomingCalls: 'calls:getIncomingCalls',
  },
  posts: {
    getFeedPosts: 'posts:getFeedPosts',
    getUnifiedFeed: 'posts:getUnifiedFeed',
    getPostById: 'posts:getPostById',
    createPost: 'posts:createPost',
    deletePost: 'posts:deletePost',
    likePost: 'posts:likePost',
    unlikePost: 'posts:unlikePost',
    hasUserLikedPost: 'posts:hasUserLikedPost',
    getUserPosts: 'posts:getUserPosts',
  },
  comments: {
    getPostComments: 'comments:getPostComments',
    createComment: 'comments:createComment',
    deleteComment: 'comments:deleteComment',
  },
  follows: {
    followUser: 'follows:followUser',
    unfollowUser: 'follows:unfollowUser',
    isFollowing: 'follows:isFollowing',
    getFollowers: 'follows:getFollowers',
    getFollowing: 'follows:getFollowing',
  },
  reactions: {
    addReaction: 'reactions:addReaction',
    removeReaction: 'reactions:removeReaction',
    getReactions: 'reactions:getReactions',
    getUserReaction: 'reactions:getUserReaction',
  },
  bookmarks: {
    addBookmark: 'bookmarks:addBookmark',
    removeBookmark: 'bookmarks:removeBookmark',
    getBookmarks: 'bookmarks:getBookmarks',
    hasUserBookmarked: 'bookmarks:hasUserBookmarked',
    getBookmarkCollections: 'bookmarks:getBookmarkCollections',
  },
  hashtags: {
    getTrendingHashtags: 'hashtags:getTrendingHashtags',
    getPostsByHashtag: 'hashtags:getPostsByHashtag',
    getHashtagByName: 'hashtags:getHashtagByName',
  },
  notifications: {
    getNotifications: 'notifications:getNotifications',
    getUnreadCount: 'notifications:getUnreadCount',
    markAsRead: 'notifications:markAsRead',
    markAllAsRead: 'notifications:markAllAsRead',
    createNotification: 'notifications:createNotification',
  },
  reposts: {
    createRepost: 'reposts:createRepost',
    deleteRepost: 'reposts:deleteRepost',
    getReposts: 'reposts:getReposts',
    hasUserReposted: 'reposts:hasUserReposted',
    getUserReposts: 'reposts:getUserReposts',
  },
  conversations: {
    getOrCreateConversation: 'conversations:getOrCreateConversation',
    getConversations: 'conversations:getConversations',
    getConversation: 'conversations:getConversation',
    muteConversation: 'conversations:muteConversation',
    deleteConversation: 'conversations:deleteConversation',
    getTotalUnreadCount: 'conversations:getTotalUnreadCount',
    searchConversations: 'conversations:searchConversations',
    createGroup: 'conversations:createGroup',
    addGroupMember: 'conversations:addGroupMember',
    removeGroupMember: 'conversations:removeGroupMember',
    leaveGroup: 'conversations:leaveGroup',
    updateGroupInfo: 'conversations:updateGroupInfo',
    promoteToAdmin: 'conversations:promoteToAdmin',
    demoteFromAdmin: 'conversations:demoteFromAdmin',
    pinMessage: 'conversations:pinMessage',
    getPinnedMessages: 'conversations:getPinnedMessages',
  },
  messages: {
    sendMessage: 'messages:sendMessage',
    getMessages: 'messages:getMessages',
    deleteMessage: 'messages:deleteMessage',
    markAsRead: 'messages:markAsRead',
    editMessage: 'messages:editMessage',
    getReadReceipts: 'messages:getReadReceipts',
    searchMessages: 'messages:searchMessages',
    reactToMessage: 'messages:reactToMessage',
  },
  presence: {
    setTyping: 'presence:setTyping',
    getTypingUsers: 'presence:getTypingUsers',
    clearStaleTyping: 'presence:clearStaleTyping',
    updateStatus: 'presence:updateStatus',
    setCustomStatus: 'presence:setCustomStatus',
    heartbeat: 'presence:heartbeat',
    getOnlineUsers: 'presence:getOnlineUsers',
    getUserPresence: 'presence:getUserPresence',
    updateOnlineStatusVisibility: 'presence:updateOnlineStatusVisibility',
  },
}
