// Mock Convex generated API
export const api = {
  polls: {
    createPoll: 'polls:createPoll',
    linkPollToPost: 'polls:linkPollToPost',
    vote: 'polls:vote',
    getPollResults: 'polls:getPollResults',
    getUserVote: 'polls:getUserVote',
    deletePoll: 'polls:deletePoll',
  },
  stories: {
    createStory: 'stories:createStory',
    getStories: 'stories:getStories',
    getStoryById: 'stories:getStoryById',
    viewStory: 'stories:viewStory',
    getStoryViewers: 'stories:getStoryViewers',
    deleteStory: 'stories:deleteStory',
  },
  users: {
    updateProfile: 'users:updateProfile',
    addSkill: 'users:addSkill',
    removeSkill: 'users:removeSkill',
    getCurrentUser: 'users:getCurrentUser',
    getUserById: 'users:getUserById',
    searchUsers: 'users:searchUsers',
    createUserFromWebhook: 'users:createUserFromWebhook',
    updateUserFromWebhook: 'users:updateUserFromWebhook',
    getUserByUsername: 'users:getUserByUsername',
    getUserByIdOrUsername: 'users:getUserByIdOrUsername',
    updateNotificationPreferences: 'users:updateNotificationPreferences',
  },
  media: {
    generateUploadUrl: 'media:generateUploadUrl',
    getFileUrl: 'media:getFileUrl',
    deleteUpload: 'media:deleteUpload',
    fetchLinkPreview: 'media:fetchLinkPreview',
    resolveStorageUrls: 'media:resolveStorageUrls',
  },
  calls: {
    initiateCall: 'calls:initiateCall',
    acceptCall: 'calls:acceptCall',
    rejectCall: 'calls:rejectCall',
    endCall: 'calls:endCall',
    getCallHistory: 'calls:getCallHistory',
    getActiveCall: 'calls:getActiveCall',
    getIncomingCalls: 'calls:getIncomingCalls',
  },
  posts: {
    getFeedPosts: 'posts:getFeedPosts',
    getUnifiedFeed: 'posts:getUnifiedFeed',
    getPostById: 'posts:getPostById',
    createPost: 'posts:createPost',
    deletePost: 'posts:deletePost',
    likePost: 'posts:likePost',
    unlikePost: 'posts:unlikePost',
    hasUserLikedPost: 'posts:hasUserLikedPost',
    getUserPosts: 'posts:getUserPosts',
  },
  comments: {
    getPostComments: 'comments:getPostComments',
    getCommentReplies: 'comments:getCommentReplies',
    createComment: 'comments:createComment',
    deleteComment: 'comments:deleteComment',
  },
  communities: {
    createCommunity: 'communities:createCommunity',
    getCommunity: 'communities:getCommunity',
    getCommunities: 'communities:getCommunities',
    getMyCommunities: 'communities:getMyCommunities',
    getCommunityMembers: 'communities:getCommunityMembers',
    getCommunityPosts: 'communities:getCommunityPosts',
    joinCommunity: 'communities:joinCommunity',
    leaveCommunity: 'communities:leaveCommunity',
    requestToJoin: 'communities:requestToJoin',
    approveJoinRequest: 'communities:approveJoinRequest',
    addMember: 'communities:addMember',
    removeMember: 'communities:removeMember',
    updateMemberRole: 'communities:updateMemberRole',
    updateCommunity: 'communities:updateCommunity',
    deleteCommunity: 'communities:deleteCommunity',
  },
  follows: {
    followUser: 'follows:followUser',
    unfollowUser: 'follows:unfollowUser',
    isFollowing: 'follows:isFollowing',
    getFollowers: 'follows:getFollowers',
    getFollowing: 'follows:getFollowing',
  },
  reactions: {
    addReaction: 'reactions:addReaction',
    removeReaction: 'reactions:removeReaction',
    getReactions: 'reactions:getReactions',
    getUserReaction: 'reactions:getUserReaction',
  },
  bookmarks: {
    addBookmark: 'bookmarks:addBookmark',
    removeBookmark: 'bookmarks:removeBookmark',
    getBookmarks: 'bookmarks:getBookmarks',
    isBookmarked: 'bookmarks:isBookmarked',
    getCollections: 'bookmarks:getCollections',
    getBookmarkDetails: 'bookmarks:getBookmarkDetails',
  },
  hashtags: {
    getTrending: 'hashtags:getTrending',
    getPostsByHashtag: 'hashtags:getPostsByHashtag',
    searchHashtags: 'hashtags:searchHashtags',
    updateTrendingScores: 'hashtags:updateTrendingScores',
    getHashtagStats: 'hashtags:getHashtagStats',
  },
  notifications: {
    getNotifications: 'notifications:getNotifications',
    getUnreadCount: 'notifications:getUnreadCount',
    markAsRead: 'notifications:markAsRead',
    markAllAsRead: 'notifications:markAllAsRead',
    createNotification: 'notifications:createNotification',
  },
  reposts: {
    createRepost: 'reposts:createRepost',
    deleteRepost: 'reposts:deleteRepost',
    getReposts: 'reposts:getReposts',
    hasUserReposted: 'reposts:hasUserReposted',
    getUserReposts: 'reposts:getUserReposts',
  },
  conversations: {
    getOrCreateConversation: 'conversations:getOrCreateConversation',
    getConversations: 'conversations:getConversations',
    getConversation: 'conversations:getConversation',
    muteConversation: 'conversations:muteConversation',
    deleteConversation: 'conversations:deleteConversation',
    getTotalUnreadCount: 'conversations:getTotalUnreadCount',
    searchConversations: 'conversations:searchConversations',
    createGroup: 'conversations:createGroup',
    addGroupMember: 'conversations:addGroupMember',
    removeGroupMember: 'conversations:removeGroupMember',
    leaveGroup: 'conversations:leaveGroup',
    updateGroupInfo: 'conversations:updateGroupInfo',
    promoteToAdmin: 'conversations:promoteToAdmin',
    demoteFromAdmin: 'conversations:demoteFromAdmin',
    pinMessage: 'conversations:pinMessage',
    getPinnedMessages: 'conversations:getPinnedMessages',
  },
  messages: {
    sendMessage: 'messages:sendMessage',
    getMessages: 'messages:getMessages',
    deleteMessage: 'messages:deleteMessage',
    markAsRead: 'messages:markAsRead',
    editMessage: 'messages:editMessage',
    getReadReceipts: 'messages:getReadReceipts',
    searchMessages: 'messages:searchMessages',
    reactToMessage: 'messages:reactToMessage',
  },
  presence: {
    setTyping: 'presence:setTyping',
    getTypingUsers: 'presence:getTypingUsers',
    clearStaleTyping: 'presence:clearStaleTyping',
    updateStatus: 'presence:updateStatus',
    setCustomStatus: 'presence:setCustomStatus',
    heartbeat: 'presence:heartbeat',
    getOnlineUsers: 'presence:getOnlineUsers',
    getUserPresence: 'presence:getUserPresence',
    updateOnlineStatusVisibility: 'presence:updateOnlineStatusVisibility',
  },
  suggestions: {
    getSuggestions: 'suggestions:getSuggestions',
    dismissSuggestion: 'suggestions:dismissSuggestion',
    refreshSuggestions: 'suggestions:refreshSuggestions',
  },
  feedRanking: {
    getRankedFeed: 'feedRanking:getRankedFeed',
    getChronologicalFeed: 'feedRanking:getChronologicalFeed',
    getTrendingFeed: 'feedRanking:getTrendingFeed',
  },
  recommendations: {
    getRecommendedPosts: 'recommendations:getRecommendedPosts',
    getSimilarPosts: 'recommendations:getSimilarPosts',
    getTrendingInSkill: 'recommendations:getTrendingInSkill',
    getPopularInUniversity: 'recommendations:getPopularInUniversity',
  },
  search: {
    universalSearch: 'search:universalSearch',
    searchPosts: 'search:searchPosts',
    searchUsersEnhanced: 'search:searchUsersEnhanced',
    searchHashtags: 'search:searchHashtags',
  },
  skillEndorsements: {
    endorseSkill: 'skillEndorsements:endorseSkill',
    removeEndorsement: 'skillEndorsements:removeEndorsement',
    getEndorsements: 'skillEndorsements:getEndorsements',
    getMyEndorsements: 'skillEndorsements:getMyEndorsements',
  },
  matching: {
    findExperts: 'matching:findExperts',
    findStudyPartners: 'matching:findStudyPartners',
    findMentors: 'matching:findMentors',
  },
  events: {
    createEvent: 'events:createEvent',
    updateEvent: 'events:updateEvent',
    deleteEvent: 'events:deleteEvent',
    rsvpEvent: 'events:rsvpEvent',
    getEvent: 'events:getEvent',
    getUpcomingEvents: 'events:getUpcomingEvents',
    getPastEvents: 'events:getPastEvents',
    getUserEvents: 'events:getUserEvents',
    getCommunityEvents: 'events:getCommunityEvents',
    getEventAttendees: 'events:getEventAttendees',
  },
}
